//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public string MABL { get; set; }
        public string MAMH { get; set; }
        public string NOIDUNG { get; set; }
        public System.DateTime NGAYGUI { get; set; }
        public string TENKH { get; set; }
    
        public virtual MATHANG MATHANG { get; set; }
    }
}
