//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BINHLUAN
    {
        public string MABL { get; set; }
        public string MAMH { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(250, MinimumLength =10, ErrorMessage = "Bịnh luận phải có 10 - 250 ký tự")]
        public string NOIDUNG { get; set; }
        public System.DateTime NGAYGUI { get; set; }
        [StringLength(20, ErrorMessage = "Không vượt quá 20 ký tự")]
        public string TENKH { get; set; }
    
        public virtual MATHANG MATHANG { get; set; }
    }
}
