//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTGIOHANG
    {
        public string MAGH { get; set; }
        public string MAMH { get; set; }
        public byte SOLUONG { get; set; }
        public int THANHTIEN { get; set; }
    
        public virtual GIOHANG GIOHANG { get; set; }
        public virtual MATHANG MATHANG { get; set; }
    }
}
