//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DANHGIA
    {
        public string MADG { get; set; }
        public string MAMH { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [Range(1, 5, ErrorMessage = "Phải chọn từ 1 đến 5 sao")]
        public byte SAO { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string TENKH { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [StringLength(250, MinimumLength = 80, ErrorMessage = "Phải có ít nhất 80 - 250 ký tự")]
        public string NOIDUNG { get; set; }
    
        public virtual MATHANG MATHANG { get; set; }
    }
}
