//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIOHANG()
        {
            this.CTGIOHANGs = new HashSet<CTGIOHANG>();
        }
    
        public string MAGH { get; set; }
        public string MATP { get; set; }
        public string MAPTTT { get; set; }
        public bool TRANGTHAI { get; set; }
        public System.DateTime NGAYXUAT { get; set; }
        public long TONGTIEN { get; set; }
        public string HOTENKH { get; set; }
        public string SDTKH { get; set; }
        public bool GIOITINHKH { get; set; }
        public string LOINHAN { get; set; }
        public string DIACHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTGIOHANG> CTGIOHANGs { get; set; }
        public virtual PHUONGTHUCTHANHTOAN PHUONGTHUCTHANHTOAN { get; set; }
        public virtual THANHPHO THANHPHO { get; set; }
    }
}
