//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GIOHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIOHANG()
        {
            this.CTGIOHANGs = new HashSet<CTGIOHANG>();
        }
    
        public string MAGH { get; set; }
        public string MATP { get; set; }
        public string MAPTTT { get; set; }
        public bool TRANGTHAI { get; set; }
        public System.DateTime NGAYXUAT { get; set; }
        public long TONGTIEN { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(100, MinimumLength = 10, ErrorMessage = "Tên phải có 10 - 100 ký tự")]
        public string HOTENKH { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(15, MinimumLength = 8, ErrorMessage = "SDT phải có 8 - 15 số")]
        public string SDTKH { get; set; }
        public bool GIOITINHKH { get; set; }
        [StringLength(250, ErrorMessage = "Lời nhắn không quá 250 ký tự")]
        public string LOINHAN { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(250, MinimumLength = 20, ErrorMessage = "Địa chỉ phải có 20 - 250 ký tự")]
        public string DIACHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTGIOHANG> CTGIOHANGs { get; set; }
        public virtual PHUONGTHUCTHANHTOAN PHUONGTHUCTHANHTOAN { get; set; }
        public virtual PHUONGXA PHUONGXA { get; set; }
    }
}
