//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATHANG()
        {
            this.ANHMINHHOAs = new HashSet<ANHMINHHOA>();
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.CTGIOHANGs = new HashSet<CTGIOHANG>();
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.THONGSOKYTHUATs = new HashSet<THONGSOKYTHUAT>();
        }
    
        public string MAMH { get; set; }
        public string MALOAI { get; set; }
        public string MANSX { get; set; }
        public string TENMH { get; set; }
        public string ANH { get; set; }
        public int DONGIA { get; set; }
        public string MAU { get; set; }
        public double GIAMGIA { get; set; }
        public string GHICHU { get; set; }
        public string GIOITHIEUMH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANHMINHHOA> ANHMINHHOAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTGIOHANG> CTGIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        public virtual LOAIMATHANG LOAIMATHANG { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGSOKYTHUAT> THONGSOKYTHUATs { get; set; }
    }
}
