//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class MATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATHANG()
        {
            this.ANHMINHHOAs = new HashSet<ANHMINHHOA>();
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.CTGIOHANGs = new HashSet<CTGIOHANG>();
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.THONGSOKYTHUATs = new HashSet<THONGSOKYTHUAT>();
        }
        [DisplayName("Mã mặt hàng")]
        public string MAMH { get; set; }
        [Required]
        [DisplayName("Loại mặt hàng")]
        public string MALOAI { get; set; }
        [Required]
        [DisplayName("Nhà sản xuất")]
        public string MANSX { get; set; }
        [Required]
        [DisplayName("Tên mặt hàng")]
        public string TENMH { get; set; }
        [DisplayName("Ảnh đại diện")]
        public string ANH { get; set; }
        [DisplayName("Đơn giá")]
        public int DONGIA { get; set; }
        [Required]
        [DisplayName("Màu")]
        public string MAU { get; set; }
        [Required]
        [DisplayName("Giảm giá")]
        [Range(0.0, 100.0, ErrorMessage  = "Sai giá trị")]
        public double GIAMGIA { get; set; }
        [Required]
        [AllowHtml]
        public string GHICHU { get; set; }
        [Required]
        [AllowHtml]
        public string GIOITHIEUMH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANHMINHHOA> ANHMINHHOAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTGIOHANG> CTGIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        public virtual LOAIMATHANG LOAIMATHANG { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGSOKYTHUAT> THONGSOKYTHUATs { get; set; }
    }
}
