//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PHUONGXA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHUONGXA()
        {
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
    
        public string MAPX { get; set; }
        public string MAQH { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [StringLength(20, ErrorMessage = "Tối đa 200 ký tự")]
        [DisplayName("Tên Phường / Xã")]
        public string TENPX { get; set; }
    
        public virtual QUANHUYEN QUANHUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
    }
}
