//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGSOKYTHUAT
    {
        public string MATS { get; set; }
        public string MAMH { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual MATHANG MATHANG { get; set; }
    }
}
